#pragma once

#include "Game/GameVersion.h"

#include <array>

enum GameAddressID
{
	GAID_LATE_GAME_UPDATE = 0,
	GAID_LATE_GAME_UPDATE_RET,
	GAID_GAME_SHUTDOWN,

	GAID_WND_PROC,
	GAID_UPDATE_KEYBOARD_INPUT,

	GAID_PRE_RENDER,

	GAID_CHECK_FOR_TRIGGERS,
	GAID_FETCH_DOOR_ROOM_DATA,
	GAID_FETCH_DOOR_ROOM_DATA_OFFSET,
	GAID_EXECUTE_TRIGGER,
	GAID_0041FD70,

	GAID_INSTANT_TYPE_WRITER_MENU,
	GAID_INVALID_SAVE_FIX,

	GAID_DOOR_SKIP_ANIM,
	GAID_DOOR_SKIP_RENDER,
	GAID_DOOR_SKIP_ANIM_START,
	GAID_DOOR_SKIP_SOUNDS,
	GAID_DOOR_SKIP_LAB_ELEVATOR_FIX,

	GAID_CHEAT_INFINITE_AMMO,
	GAID_CHEAT_INFINITE_HEALTH,

	GAID_INVENTORY,

	GAID_COUNT
};

void InitGameAddresses(GameVersion gameVersion);

extern std::array<size_t, GAID_COUNT> GameAddresses;