#pragma once

#include <array>

enum class ItemId
{
	None						= 0,
	JillsKnife					= 1,
	ChrisKnife					= 2,
	Pistol						= 3,
	SelfDefenseGun				= 4,
	SamuraiEdge					= 5,
	Shotgun						= 6,
	GrenadeLauncherNormal		= 7,
	GrenadeLauncherAcid			= 8,
	GrenadeLauncherIncendiary	= 9,
	RocketLauncher				= 10,
	Magnum						= 11,
	FlameThrower				= 12,
	AssaultShotgun				= 13,
	UnlimitedRocketLauncher		= 14,
	BarrysMagnum				= 15,
	GrenadeShells				= 16,
	HandgunMagazine				= 17,
	ShotgunShells				= 18,
	AcidShells					= 19,
	IncendiaryShells			= 20,

	GoldenArrow					= 21,
	BookOfCurses				= 22,
	Coin						= 23,
	Collar						= 24,

	MagnumRounds				= 25,

	Broach						= 26,
	FuelCanteen					= 27,
	Arrowhead					= 28,
	ImitationOfKey				= 29,
	GalleryKey					= 30,
	FuelCapsuleArmed			= 31,
	MusicalScore				= 32,

	FirstAidSpray				= 33,
	GreenHerb					= 34,
	RedHerb						= 35,
	BlueHerb					= 36,
	Green2HerbsMix				= 37,
	Green3HerbsMix²				= 38,
	GreenRedHerbsMix			= 39,
	GreenRedBlueHerbsMix		= 40,
	GreebBlueHerbsMix			= 41,
	Green2BlueHerbsMix			= 42,

	LockPick					= 43,
	SmallKey					= 44,
	SwordKey					= 45,
	ArmorKey					= 46,
	ShieldKey					= 47,
	HelmetKey					= 48,
	Key001						= 49,
	Key003						= 50,

	MedalOfEagle				= 51,
	MedalOfWolf					= 52,
	StoneMetalObject			= 53,
	PowerKey					= 54,
	MasterKey					= 55,
	StarCrest					= 56,
	WindCrest					= 57,
	SunCrest					= 58,
	MoonCrest					= 59,
	SquareCrank					= 60,
	HexCrank					= 61,

	ClosetKey					= 62,

	EmblemKey					= 63,
	StoneRing					= 64,
	MetalObject					= 65,

	Knife						= 66,

	Battery						= 67,
	InkRibbon					= 68,
	WoodenEmblem				= 69,
	GoldenEmblem				= 70,
	SheetMusic					= 71,
	RedJewel					= 72,
	BlueJewel					= 73,
	YellowJewel					= 74,
	BrokenShotgun				= 75,
	Chemical					= 76,
	Lighter						= 77,
	Serum						= 78,
	Transceiver					= 79,
	EmptyBottle					= 80,
	Water						= 81,
	UMBNo3						= 82,
	NP004						= 83,
	Yellow6						= 84,
	UMBNo7						= 85,
	UMBNo10						= 86,
	VP017						= 87,
	VJOLT						= 88,

	UnusedGrenadeShells			= 89,

	RedBook						= 90,
	LastBookVol1				= 91,
	LastBookVol2				= 92,
	MODisk1						= 93,
	MODisk2						= 94,
	MODisk3						= 95,
	DogWhistle					= 96,
	FuseUnit					= 97,
	Capsule						= 98,
	JewelryBoxStoneRing			= 99,
	InsecticideSpray			= 100,
	FirstAidBoxSpray			= 101,
	JewelryBoxBroach			= 102,
	JewelryBoxMask				= 103,
	FirstAidfBoxGreen			= 104,
	FirstAidfBoxBlue			= 105,
	SignalRockets				= 106,
	BrokenFlameThrower			= 107,
	WoodenMount					= 108,
	SlideFilter					= 109,
	ControlRoomKey				= 110,
	FuelCapsuleEmpty			= 111,

	Dagger						= 112,
	FlashGrenade				= 113,
	StunGun						= 114,

	BeeSpecimen					= 115,
	LureOfABee					= 116,
	Fishhook					= 117,
	LureOfABeeFishhook			= 118,
	XRay1						= 119,
	XRay2						= 120,

	BatteryPack					= 121,

	Shaft						= 122,
	Cylinder					= 123,
	CylinderShaft				= 124,
	DeathMaskEMN				= 125,
	DeathMaskEyes				= 126,
	DeathMaskNose				= 127,
	DeathMaskMouth				= 128,
	MusicalScore2				= 129,

	Map							= 130,

	FirstAidBoxGreenBlue		= 131,
	FirstAidBoxGreen2			= 132,

	Count						= 133
};

constexpr const int ItemCount = static_cast<int>(ItemId::Count);

constexpr const std::array ItemNames =
{
	"Nothing",
	"Jill's Knife",
	"Chris' Knife",
	"Pistol",
	"Self defense gun",
	"Unlimited Samurai Edge",
	"Shotgun",
	"Grenade Launcher (explosive)",
	"Grenade Launcher (acid)",
	"Grenade Launcher (incendiary)",
	"Rocket Launcher",
	"Magnum",
	"Flame Thrower",
	"Assault Shotgun",
	"Unlimited Rocket Launcher",
	"Barry's Magnum",

	"Grenade Shells",
	"Handgun Magazine",
	"Shotgun Shells",
	"Acid Shells",
	"Incendiary Shells",

	"Golden Arrow",
	"Book of Curses",
	"Coin",
	"Collar",

	"Magnum Rounds",
	"Broach",
	"Fuel Canteen",
	"Arrowhead",
	"Imitation of a key",
	"Gallery Key",
	"Fuel Capsule (armed)",
	"Musical Score",

	"First Aid Spray",
	"Green Herb",
	"Red Herb",
	"Blue Herb",
	"2 Green Herbs Mix",
	"3 Green Herbs Mix",
	"Green & Red Herbs Mix",
	"Green, Red & Blue Herbs Mix",
	"Green & Blue Herbs Mix",
	"2 Green & Blue Herbs Mix",

	"Lockpick",
	"Small Key",
	"Sword Key",
	"Armor Key",
	"Shield Key",
	"Helmet Key",
	"001 Key",
	"003 Key",

	"Medal of Eagle",
	"Medal of Wolf",
	"Stone & Metal Object",
	"Power Key",
	"Master Key",
	"Star Crest",
	"Wind Crest",
	"Sun Crest",
	"Moon Crest",
	"Square Crank",
	"Hexagonal Crank",

	"Closet Key",

	"Emblem Key",
	"Stone Ring",
	"Metal Object",

	"Knife (Black Tiger)",

	"Battery",
	"Ink Ribbon",
	"Wooden Emblem",
	"Golden Emblem",
	"Sheet Music",
	"Red Jewel",
	"Blue Jewel",
	"Yellow Jewel",
	"Broken Shotgun",
	"Chemical",
	"Lighter",
	"Serum",
	"Transceiver",
	"Empty Bottle",
	"Water",
	"UMB No. 3",
	"NP-004",
	"Yellow-6",
	"UMB No. 7",
	"UMB No. 10",
	"VP-017",
	"V-JOLT",

	"Unused Grenade Shells",

	"Red Book",
	"Last Book Vol. 1",
	"Last Book Vol. 2",
	"MO Disk 1",
	"MO Disk 2",
	"MO Disk 3",
	"Dog Whistle",
	"Fuse Unit",
	"Capsule (empty)",
	"Jewelry Box (Stone Ring)",
	"Insecticide Spray",
	"First Aid Box (Spray)",
	"Jewelry Box (Broach)",
	"Jewerly Box (Mask)",
	"First Aid Box (Green Herb)",
	"First Aid Box (Blue Herb)",
	"Signal Rockets",
	"Broken Flamethrower",
	"Wooden Mount",
	"Slide Filter",
	"Control Room Key",
	"Fuel Capsule (empty)",

	"Dagger",
	"Flash Grenade",
	"Stun Gun",

	"Bee Specimen",
	"Lure of a bee",
	"Fishhook",
	"Lure of a bee (with fishhook)",
	"X-Ray 1",
	"X-Ray 2",
	"Battery Pack",
	"Shaft",
	"Cylinder",
	"Cylinder Shaft",
	"Death Mask (EMN)",
	"Death Mask (Eyes)",
	"Death Mask (Nose)",
	"Death Mask (Mouth)",
	"Musical Score",

	"Map",

	"First Aid Box (Green + Blue)",
	"First Aid Box (Green x2)"
};

static_assert(ItemCount == ItemNames.size());